/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BillRouteRouteImport } from './routes/bill/route'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as MenuSideIndexRouteImport } from './routes/menu/$side/index'
import { Route as MenuSideCategoryIdRouteImport } from './routes/menu/$side/$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BillRouteRoute = BillRouteRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSideIndexRoute = MenuSideIndexRouteImport.update({
  id: '/menu/$side/',
  path: '/menu/$side/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSideCategoryIdRoute = MenuSideCategoryIdRouteImport.update({
  id: '/menu/$side/$categoryId',
  path: '/menu/$side/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bill': typeof BillRouteRoute
  '/about': typeof AboutRoute
  '/cafe': typeof CafeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservation': typeof ReservationRoute
  '/restaurant': typeof RestaurantRoute
  '/services': typeof ServicesRoute
  '/menu/': typeof MenuIndexRoute
  '/menu/$side/$categoryId': typeof MenuSideCategoryIdRoute
  '/menu/$side/': typeof MenuSideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bill': typeof BillRouteRoute
  '/about': typeof AboutRoute
  '/cafe': typeof CafeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservation': typeof ReservationRoute
  '/restaurant': typeof RestaurantRoute
  '/services': typeof ServicesRoute
  '/menu': typeof MenuIndexRoute
  '/menu/$side/$categoryId': typeof MenuSideCategoryIdRoute
  '/menu/$side': typeof MenuSideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bill': typeof BillRouteRoute
  '/about': typeof AboutRoute
  '/cafe': typeof CafeRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservation': typeof ReservationRoute
  '/restaurant': typeof RestaurantRoute
  '/services': typeof ServicesRoute
  '/menu/': typeof MenuIndexRoute
  '/menu/$side/$categoryId': typeof MenuSideCategoryIdRoute
  '/menu/$side/': typeof MenuSideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bill'
    | '/about'
    | '/cafe'
    | '/contact'
    | '/gallery'
    | '/reservation'
    | '/restaurant'
    | '/services'
    | '/menu/'
    | '/menu/$side/$categoryId'
    | '/menu/$side/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bill'
    | '/about'
    | '/cafe'
    | '/contact'
    | '/gallery'
    | '/reservation'
    | '/restaurant'
    | '/services'
    | '/menu'
    | '/menu/$side/$categoryId'
    | '/menu/$side'
  id:
    | '__root__'
    | '/'
    | '/bill'
    | '/about'
    | '/cafe'
    | '/contact'
    | '/gallery'
    | '/reservation'
    | '/restaurant'
    | '/services'
    | '/menu/'
    | '/menu/$side/$categoryId'
    | '/menu/$side/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillRouteRoute: typeof BillRouteRoute
  AboutRoute: typeof AboutRoute
  CafeRoute: typeof CafeRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ReservationRoute: typeof ReservationRoute
  RestaurantRoute: typeof RestaurantRoute
  ServicesRoute: typeof ServicesRoute
  MenuIndexRoute: typeof MenuIndexRoute
  MenuSideCategoryIdRoute: typeof MenuSideCategoryIdRoute
  MenuSideIndexRoute: typeof MenuSideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill': {
      id: '/bill'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof BillRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$side/': {
      id: '/menu/$side/'
      path: '/menu/$side'
      fullPath: '/menu/$side/'
      preLoaderRoute: typeof MenuSideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$side/$categoryId': {
      id: '/menu/$side/$categoryId'
      path: '/menu/$side/$categoryId'
      fullPath: '/menu/$side/$categoryId'
      preLoaderRoute: typeof MenuSideCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillRouteRoute: BillRouteRoute,
  AboutRoute: AboutRoute,
  CafeRoute: CafeRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ReservationRoute: ReservationRoute,
  RestaurantRoute: RestaurantRoute,
  ServicesRoute: ServicesRoute,
  MenuIndexRoute: MenuIndexRoute,
  MenuSideCategoryIdRoute: MenuSideCategoryIdRoute,
  MenuSideIndexRoute: MenuSideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
